### ISSUE TITLE
CORS Error

### ISSUE THREAD

**Issue by overflowwebdesigns** [JamesUgbanu/react-native-woocommerce-api#19]
I am using the examples in the documentation to setup my connection.  It all seems to go well until I try and pull data (in my case products)

I get CORS errors.

Access to fetch at 'MY WOOSITE' from origin 'http://localhost:3000' has been blocked by CORS policy: Request header field cache-control is not allowed by Access-Control-Allow-Headers in preflight response.

Is there a way around this?  My app that is trying to access the API is on localhost:3000 still as I am in development.

**Comment by JamesUgbanu** [comment]
This issue is beyond the scope of this library as this is a server error and it is due to your sever blocking all API calls. However, paste the below function in your WordPress **function.php**. Change the origin to your url.

`add_action('init', 'handle_preflight');
function handle_preflight() {
    $origin = get_http_origin();
    if ($origin === 'https://yourfrontenddomain') {
        header("Access-Control-Allow-Origin: yourfrontenddomain");
        header("Access-Control-Allow-Methods: POST, GET, OPTIONS, PUT, DELETE");
        header("Access-Control-Allow-Credentials: true");
        header('Access-Control-Allow-Headers: Origin, X-Requested-With, X-WP-Nonce, Content-Type, Accept, Authorization');
        if ('OPTIONS' == $_SERVER['REQUEST_METHOD']) {
            status_header(200);
            exit();
        }
    }
}
add_filter('rest_authentication_errors', 'rest_filter_incoming_connections');
function rest_filter_incoming_connections($errors) {
    $request_server = $_SERVER['REMOTE_ADDR'];
    $origin = get_http_origin();
    if ($origin !== 'https://yourfrontenddomain') return new WP_Error('forbidden_access', $origin, array(
        'status' => 403
    ));
    return $errors;
}`

**Comment by JamesUgbanu** [comment]
I will keep
